version: '3.8'

services:
  # Servicio del Backend (Django)
  backend:
    build: ./backend
    container_name: django_backend
    # El comando se ejecutará directamente desde el Dockerfile, pero lo dejamos aquí por claridad.
    command: gunicorn taskmanager.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"

  # Servicio del Frontend (Angular)
  frontend:
    build: ./frontend
    container_name: angular_frontend
    ports:
      # Expone tu app de Angular en http://localhost:4200
      - "4200:80"
    depends_on:
      - backend